# Generated by Django 3.1.5 on 2021-03-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20210319_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-created_date'], 'verbose_name': 'Bloqlar', 'verbose_name_plural': 'Bloqlar'},
        ),
    ]
