# Generated by Django 3.1.5 on 2021-03-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20210319_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': 'Bloqlar', 'verbose_name_plural': 'Bloqlar'},
        ),
    ]
