# Generated by Django 3.1.5 on 2021-02-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Müştəri')),
                ('phone', models.CharField(max_length=20, verbose_name='Tel')),
                ('message', models.CharField(max_length=200, verbose_name='İstək mətni')),
                ('created_date', models.DateTimeField(verbose_name='Tarix')),
                ('status', models.BooleanField(default=False, verbose_name='Zəng olundu')),
            ],
            options={
                'verbose_name': 'Zəng gözləyən müştərilər',
                'verbose_name_plural': 'Zəng gözləyən müştərilər',
            },
        ),
    ]
