# Generated by Django 3.1.5 on 2021-03-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Bloq', 'verbose_name_plural': 'Bloq'},
        ),
    ]
