# Generated by Django 3.1.5 on 2021-01-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_id', models.CharField(max_length=100)),
                ('product_id', models.IntegerField(max_length=1000)),
                ('name', models.CharField(max_length=50, verbose_name='Adı')),
                ('size', models.CharField(max_length=10, verbose_name='Ölçüsü')),
                ('image', models.ImageField(default=None, upload_to='static/product_images/', verbose_name='Şəkil')),
                ('price', models.FloatField(default=0.0, verbose_name='Qiymət AZN')),
                ('count', models.IntegerField(default=0, verbose_name='Sayı')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Adı')),
            ],
            options={
                'verbose_name': 'Sifarişlər',
                'verbose_name_plural': 'Sifarişlər',
            },
        ),
    ]
