# Generated by Django 3.1.5 on 2021-01-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Məhsullar'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
