# Generated by Django 3.1.5 on 2021-01-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20210130_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Yerinə yetirildi'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Sifarişçi'),
        ),
    ]
