# Generated by Django 3.1.5 on 2021-01-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20210130_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Sifarişçi'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Məhsullar'),
        ),
    ]
