# Generated by Django 3.1.5 on 2021-01-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_auto_20210131_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Tel'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Sifarişçi'),
        ),
    ]
