# Generated by Django 3.1.5 on 2021-01-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_auto_20210131_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
