# Generated by Django 3.1.5 on 2021-03-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_auto_20210131_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Qiymət AZN'),
        ),
    ]
