# Generated by Django 3.1.5 on 2021-01-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(default=None, upload_to='static/product_images/', verbose_name='Şəkil: 1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(default=None, upload_to='static/product_images/', verbose_name='Şəkil: 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(default=None, upload_to='static/product_images/', verbose_name='Şəkil: 3'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image4',
            field=models.ImageField(default=None, upload_to='static/product_images/', verbose_name='Şəkil: 4'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image5',
            field=models.ImageField(default=None, upload_to='static/product_images/', verbose_name='Şəkil: 5'),
        ),
    ]
