# Generated by Django 3.1.5 on 2021-01-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210126_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='detail_main',
            field=models.TextField(max_length=500, verbose_name='Əsas məlumat'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(default=None, help_text='425x425 ölçüsündə olmalıdır!', upload_to='static/product_images/', verbose_name='Şəkil 1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.ImageField(default=None, help_text='425x425 ölçüsündə olmalıdır!', upload_to='static/product_images/', verbose_name='Şəkil 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.ImageField(default=None, help_text='425x425 ölçüsündə olmalıdır!', upload_to='static/product_images/', verbose_name='Şəkil 3'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image4',
            field=models.ImageField(default=None, help_text='425x425 ölçüsündə olmalıdır!', upload_to='static/product_images/', verbose_name='Şəkil 4'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image5',
            field=models.ImageField(default=None, help_text='425x425 ölçüsündə olmalıdır!', upload_to='static/product_images/', verbose_name='Şəkil 5'),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Məhsulu görünən et'),
        ),
    ]
