# Generated by Django 3.1.5 on 2021-02-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210127_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='Endirimli'),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
