# Generated by Django 3.1.5 on 2021-03-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210308_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='company',
            field=models.CharField(choices=[('all', 'Ümumi'), ('tepe', 'TePe'), ('bilimplant', 'Bilimplant'), ('miradent', 'Miradent')], default='all', help_text='Hansı saytda görünməsini istəyirsən?', max_length=15, null=True, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Hər kəsə açıq'),
        ),
    ]
