# Generated by Django 3.1.5 on 2021-03-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210318_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_old',
            field=models.FloatField(default=None, null=True, verbose_name='Köhnə qiymət AZN'),
        ),
    ]
