# Generated by Django 3.1.5 on 2021-03-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_products_price_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price_old',
            field=models.FloatField(default=0, null=True, verbose_name='Köhnə qiymət AZN'),
        ),
    ]
