# Generated by Django 3.1.5 on 2021-03-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210318_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price_old',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Köhnə qiymət AZN'),
        ),
    ]
