# Generated by Django 3.1.5 on 2021-03-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210319_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Qiymət AZN'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_old',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name='Köhnə qiymət AZN'),
        ),
    ]
