# Generated by Django 3.1.5 on 2021-03-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210320_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price_old',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name='Köhnə qiymət AZN'),
        ),
    ]
