# Generated by Django 3.1.5 on 2021-03-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210320_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Yoxdursa boş burax', max_digits=6, verbose_name='Endirim'),
        ),
    ]
