# Generated by Django 3.1.5 on 2021-03-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_products_price_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price_old',
        ),
    ]
