# Generated by Django 3.1.5 on 2021-03-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_products_price_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='stock',
        ),
    ]
