# Generated by Django 3.1.5 on 2021-03-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_products_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Adı')),
                ('precent', models.IntegerField(verbose_name='Endirim faizi %')),
            ],
        ),
    ]
