# Generated by Django 3.1.5 on 2021-03-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20210326_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discounts',
            options={'ordering': ['id'], 'verbose_name': 'Endirimlər', 'verbose_name_plural': 'Endirimlər'},
        ),
    ]
