# Generated by Django 3.1.5 on 2021-03-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210326_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_precent',
            field=models.IntegerField(default=0, null=True, verbose_name='Endirim faizi %'),
        ),
    ]
