# Generated by Django 3.1.5 on 2021-06-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_products_discount_precent'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='popular',
            field=models.BooleanField(default=False, help_text='Ana səhifədə görsənsin?', verbose_name='Ən çox satılan məhsul'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount_precent',
            field=models.IntegerField(default=0, null=True, verbose_name='Faiz'),
        ),
    ]
