# Generated by Django 3.1.5 on 2021-06-12 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_remove_products_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.products', verbose_name='Ən çox satılan məhsullar')),
            ],
            options={
                'verbose_name': 'Ən çox satılan məhsullar',
                'verbose_name_plural': 'Ən çox satılan məhsullar',
            },
        ),
    ]
