# Generated by Django 3.1.5 on 2021-06-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_popular'),
        ('products', '0014_auto_20210320_1146'),
    ]

    operations = [
    ]
